#!/usr/bin/env python3
"""
gen_healthcare_scenarios.py — Generate tests/fixtures/healthcare_scenarios.rego

Reads all JSON/YAML fixtures from
  scenarios/healthcare-ambient-ai-scribe/fixtures/
and emits a single Rego data module wrapping each fixture as a package-level
constant under `data.fixtures.healthcare.<fixture_name>`.

This allows `opa test` to load all fixtures without merge-errors, while
keeping the test data in sync with the real Use-Case scenario.

Run:
    python3 tests/fixtures/gen_healthcare_scenarios.py

Output:
    tests/fixtures/healthcare_scenarios.rego
"""
import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None

REPO_ROOT = Path(__file__).parent.parent.parent
SRC_DIR = REPO_ROOT / "scenarios" / "healthcare-ambient-ai-scribe" / "fixtures"
OUT_FILE = REPO_ROOT / "tests" / "fixtures" / "healthcare_scenarios.rego"


def to_rego_value(v, indent=1):
    """Convert a Python value into a Rego literal."""
    pad = "\t" * indent
    inner_pad = "\t" * (indent + 1)
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        escaped = v.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")
        return f"\"{escaped}\""
    if isinstance(v, list):
        if not v:
            return "[]"
        items = [to_rego_value(x, indent + 1) for x in v]
        return "[\n" + ",\n".join(f"{inner_pad}{it}" for it in items) + f",\n{pad}]"
    if isinstance(v, dict):
        if not v:
            return "{}"
        lines = []
        for k, val in v.items():
            lines.append(f"{inner_pad}\"{k}\": {to_rego_value(val, indent + 1)}")
        return "{\n" + ",\n".join(lines) + f",\n{pad}}}"
    raise ValueError(f"unsupported type: {type(v)}")


def fixture_name(path: Path) -> str:
    """Derive a valid Rego identifier from the fixture filename."""
    return path.stem.replace("-", "_").replace(".", "_")


def load_fixture(path: Path):
    text = path.read_text()
    if path.suffix == ".json":
        return json.loads(text)
    if path.suffix in (".yaml", ".yml"):
        if yaml is None:
            print(f"[skip] PyYAML not installed; cannot load {path.name}", file=sys.stderr)
            return None
        return yaml.safe_load(text)
    return None


def main() -> int:
    fixtures = sorted(SRC_DIR.glob("*"))
    out_lines = [
        "# ================================================================",
        "# Healthcare Ambient AI Scribe — Scenario Test Fixtures",
        "# ================================================================",
        "# AUTO-GENERATED by tests/fixtures/gen_healthcare_scenarios.py",
        "# Source: scenarios/healthcare-ambient-ai-scribe/fixtures/",
        "#",
        "# Every Rego unit test (policies/**/*_test.rego) imports fixtures",
        "# from this module as DSR-consistent scenario evidence:",
        "#",
        "#     import data.fixtures.healthcare.app_documentation",
        "#",
        "# Fail-variants are derived inline via `object.union`.",
        "# ================================================================",
        "",
        "package fixtures.healthcare",
        "",
        "import rego.v1",
        "",
    ]
    count = 0
    for f in fixtures:
        data = load_fixture(f)
        if data is None:
            continue
        name = fixture_name(f)
        out_lines.append(f"# --- {f.name} ---")
        out_lines.append(f"{name} := {to_rego_value(data)}")
        out_lines.append("")
        count += 1

    OUT_FILE.write_text("\n".join(out_lines))
    print(f"[ok] wrote {count} fixtures to {OUT_FILE.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
