# ================================================================
# Healthcare Ambient AI Scribe — Scenario Test Fixtures
# ================================================================
# AUTO-GENERATED by tests/fixtures/gen_healthcare_scenarios.py
# Source: scenarios/healthcare-ambient-ai-scribe/fixtures/
#
# Every Rego unit test (policies/**/*_test.rego) imports fixtures
# from this module as DSR-consistent scenario evidence:
#
#     import data.fixtures.healthcare.app_documentation
#
# Fail-variants are derived inline via `object.union`.
# ================================================================

package fixtures.healthcare

import rego.v1

# --- admission_review_compliant.json ---
admission_review_compliant := {
		"review": {
			"object": {
				"apiVersion": "apps/v1",
				"kind": "Deployment",
				"metadata": {
					"name": "ambient-ai-scribe",
					"namespace": "genaiops",
					"labels": {
						"app.kubernetes.io/name": "ambient-ai-scribe",
						"risk_class": "high",
					},
					"annotations": {
						"genaiops.io/evidence-store-connected": "true",
						"genaiops.io/hash-chain-enabled": "true",
						"genaiops.io/evidence-store-type": "postgresql_with_blob",
					},
				},
				"spec": {
					"template": {
						"metadata": {
							"labels": {
								"app.kubernetes.io/name": "ambient-ai-scribe",
								"risk_class": "high",
							},
							"annotations": {
								"genaiops.io/drift-detection-enabled": "true",
								"genaiops.io/service-monitor-configured": "true",
								"genaiops.io/evidence-store-connected": "true",
								"genaiops.io/hash-chain-enabled": "true",
								"genaiops.io/eval-passed": "true",
								"genaiops.io/eval-run-id": "eval-20260325-001",
								"prometheus.io/scrape": "true",
								"prometheus.io/port": "8080",
								"prometheus.io/path": "/metrics",
							},
						},
					},
				},
			},
		},
	}

# --- admission_review_noncompliant.json ---
admission_review_noncompliant := {
		"review": {
			"object": {
				"apiVersion": "apps/v1",
				"kind": "Deployment",
				"metadata": {
					"name": "ambient-ai-scribe-bad",
					"namespace": "genaiops",
					"labels": {
						"app.kubernetes.io/name": "ambient-ai-scribe",
					},
					"annotations": {},
				},
				"spec": {
					"template": {
						"metadata": {
							"labels": {
								"app.kubernetes.io/name": "ambient-ai-scribe",
							},
							"annotations": {
								"prometheus.io/scrape": "true",
							},
						},
					},
				},
			},
		},
	}

# --- app_documentation.json ---
app_documentation := {
		"application": {
			"name": "Ambient AI Scribe",
			"version": "1.0.0",
			"domain": "healthcare",
			"description": "Medical transcription and summarization system using LLM inference",
		},
		"risk_classification": {
			"risk_class": "high",
			"classification_reasoning": "Healthcare AI system that processes sensitive patient data during medical consultations. Classified as high-risk under EU AI Act Annex III, Nr. 5 lit. a — AI systems intended to be used as safety components in the management and operation of critical digital infrastructure, road traffic, or in the supply of water, gas, heating or electricity. The system assists medical professionals in documenting patient encounters, which directly impacts patient care quality and safety.",
			"annex_reference": "Annex III, Nr. 5 lit. a",
			"mitigation_measures": [
				"Human-in-the-loop review of all generated summaries before clinical use",
				"Automated hallucination detection via faithfulness scoring",
				"Input validation and PII detection before LLM processing",
				"Continuous drift monitoring with alerting (PSI > 0.2)",
			],
		},
		"manual_review": {
			"reviewed_by": "Dr. Sarah Chen (Compliance Officer)",
			"review_date": "2026-03-27T14:00:00Z",
			"review_method": "manual",
			"review_outcome": "confirmed",
			"review_notes": "Risk classification as high-risk (Annex III, Nr. 5a) confirmed. Classification reasoning is substantive and complete. Mitigation measures are appropriate for healthcare context.",
		},
		"conformity_assessment": {
			"declaration_available": true,
			"ce_marking_verified": true,
			"provider_documentation_received": true,
			"provider_contact": "Azure OpenAI Service — Microsoft Corporation",
		},
		"fundamental_rights_impact_assessment": {
			"fria_completed": true,
			"affected_rights": [
				"Right to health (Art. 35 EU Charter)",
				"Protection of personal data (Art. 8 EU Charter)",
				"Non-discrimination (Art. 21 EU Charter)",
			],
			"stakeholder_groups": [
				"patients",
				"medical_staff",
				"hospital_administration",
			],
			"mitigation_documented": true,
		},
		"human_oversight": {
			"oversight_model": "human-in-the-loop",
			"human_oversight_lead": "Dr. med. Compliance Officer",
			"oversight_roles": [
				{
					"role": "Medical Reviewer",
					"responsibility": "Reviews AI-generated summaries before clinical documentation",
					"authority": "Can reject, modify, or approve AI output",
				},
				{
					"role": "AI Governance Lead",
					"responsibility": "Monitors system performance, drift alerts, and compliance metrics",
					"authority": "Can suspend system operation via kill-switch",
				},
			],
			"escalation_procedure": {
				"level_1": "Medical Reviewer flags issue in application",
				"level_2": "AI Governance Lead reviews flagged cases within 24h",
				"level_3": "Chief Medical Officer decides on system suspension",
			},
			"intervention_capability": {
				"kill_switch": true,
				"output_override": true,
				"real_time_monitoring": true,
			},
		},
		"transparency": {
			"user_notification": "System clearly indicates AI-generated content with visual markers",
			"ai_content_labeling": true,
			"documentation_accessible": true,
			"intended_use_documented": true,
		},
		"data_governance": {
			"input_data_type": "medical_conversation_text",
			"data_classification": "special_category_personal_data",
			"encryption_at_rest": true,
			"encryption_in_transit": true,
			"retention_policy": "7 years per medical record retention requirements",
			"gdpr_lawful_basis": "Art. 9 Abs. 2 lit. h GDPR — healthcare provision",
		},
		"logging_configuration": {
			"logging_enabled": true,
			"event_types_captured": [
				"inference_request",
				"inference_response",
				"gate_decision",
				"error",
				"drift_alert",
			],
			"retention_period_days": 2555,
			"log_accessibility": "Evidence Store (PostgreSQL) + Azure Blob Storage (immutable)",
		},
		"monitoring": {
			"monitoring_enabled": true,
			"drift_detection_configured": true,
			"drift_metrics": [
				"psi_score",
				"js_divergence",
			],
			"drift_thresholds": {
				"psi_warning": 0.1,
				"psi_critical": 0.2,
				"js_warning": 0.05,
				"js_critical": 0.1,
			},
			"service_monitor_deployed": true,
			"alerting_configured": true,
		},
		"security": {
			"container_non_root": true,
			"privilege_escalation_disabled": true,
			"resource_limits_set": true,
			"secrets_externalized": true,
			"image_scanning_enabled": true,
			"network_policies_specified": true,
		},
		"evidence_store": {
			"connected": true,
			"hash_chain_enabled": true,
			"compliance_gate_version": "v1.0.0",
			"storage_type": "postgresql_with_blob",
			"immutability_enforced": true,
		},
		"approval": {
			"approved_by": "Prof. Dr. Weber (AI Governance Lead)",
			"approved_at": "2026-03-28T10:30:00Z",
			"approval_method": "manual",
			"approval_rationale": "FRIA reviewed and confirmed. Human oversight model (HITL) appropriate for high-risk healthcare system. Kill-switch tested and operational. Conformity assessment declaration verified against Art. 47.",
		},
		"model_info": {
			"model_name": "gpt-4o-mini",
			"model_version": "mock-v1.0.0",
			"provider": "Azure OpenAI Service",
			"deployment_mode": "api_consumer",
			"role_perspective": "deployer",
		},
	}

# --- app_documentation_edge_case.json ---
app_documentation_edge_case := {
		"application": {
			"name": "Ambient AI Scribe",
			"version": "1.0.0",
			"domain": "healthcare",
			"description": "Medical transcription and summarization system",
		},
		"risk_classification": {
			"risk_class": "",
			"classification_reasoning": "",
			"annex_reference": "",
			"mitigation_measures": [],
		},
		"manual_review": {
			"reviewed_by": "Dr. Sarah Chen",
			"review_date": "2026-03-27T14:00:00Z",
			"review_method": "manual",
			"review_outcome": "confirmed",
			"review_notes": "Classification confirmed",
		},
		"approval": {
			"approved_by": "Prof. Dr. Weber",
			"approved_at": "2026-03-28T10:30:00Z",
			"approval_method": "manual",
			"approval_rationale": "Approved",
		},
		"conformity_assessment": {
			"declaration_available": true,
			"ce_marking_verified": true,
			"provider_documentation_received": true,
			"provider_contact": "Azure OpenAI Service",
		},
		"fundamental_rights_impact_assessment": {
			"fria_completed": true,
			"affected_rights": [
				"Right to health (Art. 35 EU Charter)",
			],
			"stakeholder_groups": [
				"patients",
			],
			"mitigation_documented": true,
		},
		"human_oversight": {
			"oversight_model": "human-in-the-loop",
			"human_oversight_lead": "Dr. Compliance Officer",
			"oversight_roles": [],
			"escalation_procedure": {},
			"intervention_capability": {
				"kill_switch": true,
				"output_override": true,
				"real_time_monitoring": true,
			},
		},
		"transparency": {
			"user_notification": "System indicates AI-generated content",
			"ai_content_labeling": true,
			"documentation_accessible": true,
			"intended_use_documented": true,
		},
		"data_governance": {
			"input_data_type": "medical_conversation_text",
			"data_classification": "special_category_personal_data",
			"encryption_at_rest": true,
			"encryption_in_transit": true,
			"retention_policy": "7 years",
			"gdpr_lawful_basis": "Art. 9 Abs. 2 lit. h",
		},
		"logging_configuration": {
			"logging_enabled": true,
			"event_types_captured": [
				"inference_request",
			],
			"retention_period_days": 2555,
			"log_accessibility": "Evidence Store",
		},
		"monitoring": {
			"monitoring_enabled": true,
			"drift_detection_configured": true,
			"drift_metrics": [
				"psi_score",
			],
			"drift_thresholds": {
				"psi_critical": 0.2,
			},
			"service_monitor_deployed": true,
			"alerting_configured": true,
		},
		"security": {
			"container_non_root": true,
			"privilege_escalation_disabled": true,
			"resource_limits_set": true,
			"secrets_externalized": true,
			"image_scanning_enabled": true,
			"network_policies_specified": true,
		},
		"evidence_store": {
			"connected": true,
			"hash_chain_enabled": true,
			"compliance_gate_version": "v1.0.0",
			"storage_type": "postgresql_with_blob",
			"immutability_enforced": true,
		},
		"model_info": {
			"model_name": "gpt-4o-mini",
			"model_version": "mock-v1.0.0",
			"provider": "Azure OpenAI Service",
			"deployment_mode": "api_consumer",
			"role_perspective": "deployer",
		},
	}

# --- app_documentation_incomplete.json ---
app_documentation_incomplete := {
		"application": {
			"name": "Ambient AI Scribe",
			"version": "1.0.0",
			"domain": "healthcare",
			"description": "Medical transcription and summarization system using LLM inference",
		},
		"risk_classification": {
			"classification_reasoning": "",
			"annex_reference": "",
			"mitigation_measures": [],
		},
		"manual_review": {
			"reviewed_by": "",
			"review_date": "",
			"review_method": "",
			"review_outcome": "",
			"review_notes": "",
		},
		"conformity_assessment": {
			"declaration_available": false,
			"ce_marking_verified": false,
			"provider_documentation_received": false,
			"provider_contact": "",
		},
		"fundamental_rights_impact_assessment": {
			"fria_completed": false,
			"affected_rights": [],
			"stakeholder_groups": [],
			"mitigation_documented": false,
		},
		"human_oversight": {
			"oversight_model": "",
			"human_oversight_lead": "",
			"oversight_roles": [],
			"escalation_procedure": {},
			"intervention_capability": {
				"kill_switch": false,
				"output_override": false,
				"real_time_monitoring": false,
			},
		},
		"transparency": {
			"user_notification": "",
			"ai_content_labeling": false,
			"documentation_accessible": false,
			"intended_use_documented": false,
		},
		"data_governance": {
			"input_data_type": "medical_conversation_text",
			"data_classification": "special_category_personal_data",
			"encryption_at_rest": false,
			"encryption_in_transit": false,
			"retention_policy": "",
			"gdpr_lawful_basis": "",
		},
		"logging_configuration": {
			"logging_enabled": false,
			"event_types_captured": [],
			"retention_period_days": 0,
			"log_accessibility": "",
		},
		"monitoring": {
			"monitoring_enabled": false,
			"drift_detection_configured": false,
			"drift_metrics": [],
			"drift_thresholds": {},
			"service_monitor_deployed": false,
			"alerting_configured": false,
		},
		"security": {
			"container_non_root": false,
			"privilege_escalation_disabled": false,
			"resource_limits_set": false,
			"secrets_externalized": false,
			"image_scanning_enabled": false,
			"network_policies_specified": false,
		},
		"evidence_store": {
			"connected": false,
			"hash_chain_enabled": false,
			"compliance_gate_version": "",
			"storage_type": "",
			"immutability_enforced": false,
		},
		"approval": {
			"approved_by": "",
			"approved_at": "",
			"approval_method": "",
			"approval_rationale": "",
		},
		"model_info": {
			"model_name": "gpt-4o-mini",
			"model_version": "mock-v1.0.0",
			"provider": "Azure OpenAI Service",
			"deployment_mode": "api_consumer",
			"role_perspective": "deployer",
		},
	}

# --- app_documentation_transparency_fail.json ---
app_documentation_transparency_fail := {
		"_fixture_meta": {
			"description": "FAIL scenario for G-DEP-03 Transparency Docs Present (R007)",
			"policy": "policies/deployment/policy_transparency_docs_present.rego",
			"expected_result": "FAIL — instructions_for_deployers empty, known_limitations missing, ai_content_labeling missing",
			"scenario": "Healthcare Ambient AI Scribe — incomplete transparency documentation",
		},
		"transparency": {
			"instructions_for_deployers": "",
			"model_capabilities": "Transcription and summarization of medical consultations.",
		},
	}

# --- app_documentation_transparency_pass.json ---
app_documentation_transparency_pass := {
		"_fixture_meta": {
			"description": "PASS scenario for G-DEP-03 Transparency Docs Present (R007)",
			"policy": "policies/deployment/policy_transparency_docs_present.rego",
			"expected_result": "PASS — all transparency fields complete per Art. 13 + Art. 50",
			"scenario": "Healthcare Ambient AI Scribe — full transparency documentation",
		},
		"transparency": {
			"instructions_for_deployers": "The Ambient AI Scribe must be deployed in clinical environments with trained medical staff present. Output summaries must be reviewed by a licensed physician before inclusion in patient records. System operates as decision-support only — not autonomous diagnosis.",
			"model_capabilities": "Real-time transcription of patient-physician consultations with automated SOAP note generation. Supports English and German. Optimized for outpatient primary care settings.",
			"known_limitations": [
				"Accuracy degrades significantly in multi-speaker environments with more than 3 participants",
				"Medical terminology coverage limited to primary care — specialist jargon (oncology, cardiology) may produce errors",
				"No support for dialects or heavy accents in current model version",
				"Latency increases above 3s for consultations exceeding 45 minutes",
			],
			"ai_content_labeling": {
				"enabled": true,
				"method": "Metadata tag in FHIR DocumentReference.category",
				"label_text": "AI-generated summary — review required",
			},
		},
	}

# --- data_documentation_provenance_fail.json ---
data_documentation_provenance_fail := {
		"_fixture_meta": {
			"description": "FAIL scenario for G-DEP-01 Data Provenance Documented (R002)",
			"policy": "policies/pre-deployment/policy_data_provenance_documented.rego",
			"expected_result": "FAIL — sources empty, preprocessing_steps missing, data_version missing",
			"scenario": "Healthcare Ambient AI Scribe — incomplete data documentation",
		},
		"data_provenance": {
			"collection_methods": [
				"clinical_transcription_corpus",
			],
			"sources": [],
		},
	}

# --- data_documentation_provenance_pass.json ---
data_documentation_provenance_pass := {
		"_fixture_meta": {
			"description": "PASS scenario for G-DEP-01 Data Provenance Documented (R002)",
			"policy": "policies/pre-deployment/policy_data_provenance_documented.rego",
			"expected_result": "PASS — all data provenance fields complete",
			"scenario": "Healthcare Ambient AI Scribe — training data fully documented",
		},
		"data_provenance": {
			"collection_methods": [
				"clinical_transcription_corpus",
				"synthetic_augmentation",
			],
			"sources": [
				{
					"id": "DS-001",
					"name": "De-identified Clinical Transcripts",
					"origin": "Partner Hospital Network (anonymized)",
					"license": "Data Use Agreement v2.1",
				},
				{
					"id": "DS-002",
					"name": "Synthetic Medical Dialogues",
					"origin": "Internal Generation Pipeline",
					"license": "Internal — no external restrictions",
				},
			],
			"preprocessing_steps": [
				"PHI removal via NER pipeline",
				"Text normalization (lowercase, punctuation standardization)",
				"Tokenization (SentencePiece, 32k vocab)",
			],
			"data_version": "v2.3.1-2026Q1",
		},
	}

# --- decision_log_gpre01_manual.json ---
decision_log_gpre01_manual := {
		"gate_id": "G-PRE-01",
		"decision": "PASS",
		"decision_method": "MANUAL",
		"reviewed_by": "Dr. Sarah Chen (Compliance Officer)",
		"review_date": "2026-03-28T10:30:00Z",
		"review_outcome": "Risk classification confirmed as high-risk (Annex III, Nr. 5c)",
		"rationale": "Healthcare AI system processes sensitive patient data during medical consultations. System classifies as high-risk under EU AI Act Annex III Nr. 5c (AI systems intended for use in healthcare). Risk mitigation measures documented in risk_classification_report_v1.pdf. Manual review confirms automated risk classification is correct.",
		"evidence_refs": [
			"risk_classification_report_v1.pdf",
			"impact_assessment_ambient_scribe_v1.pdf",
		],
		"payload_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
		"reviewer_role": "Compliance Officer",
		"review_type": "risk_classification_confirmation",
		"comment": "Automated Conftest check verified documentation completeness. This manual review confirms the substantive correctness of the risk classification and the adequacy of mitigation measures.",
	}

# --- decision_log_gpre05_manual.json ---
decision_log_gpre05_manual := {
		"gate_id": "G-PRE-05",
		"decision": "PASS",
		"decision_method": "MANUAL",
		"reviewed_by": "Prof. Dr. Weber (AI Governance Lead)",
		"review_date": "2026-03-28T11:00:00Z",
		"review_outcome": "Strategic governance approval granted for production deployment",
		"rationale": "Governance board reviewed the Ambient AI Scribe system against organizational AI strategy and regulatory readiness. All pre-deployment gates (G-PRE-01 through G-PRE-04) have passed. Risk classification (high-risk) has been confirmed by Compliance Officer. Business case approved with conditions: quarterly re-evaluation, mandatory incident reporting, and human-in-the-loop for clinical summaries.",
		"evidence_refs": [
			"governance_board_minutes_2026-03-28.pdf",
			"ai_strategy_alignment_checklist_v2.pdf",
			"deployment_readiness_assessment.pdf",
		],
		"payload_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
		"reviewer_role": "AI Governance Lead",
		"review_type": "strategic_governance_approval",
		"approval_conditions": [
			"Quarterly re-evaluation of risk classification",
			"Mandatory incident reporting per Art. 26.5",
			"Human-in-the-loop for clinical summary generation",
		],
		"comment": "Automated Conftest check verified governance documentation completeness. This manual approval confirms strategic alignment and authorizes progression to deployment phase.",
	}

# --- deployment_compliant.yaml ---
deployment_compliant := {
		"apiVersion": "apps/v1",
		"kind": "Deployment",
		"metadata": {
			"name": "ambient-ai-scribe",
			"namespace": "genaiops",
			"labels": {
				"app.kubernetes.io/name": "ambient-ai-scribe",
				"app.kubernetes.io/version": "1.0.0",
				"risk_class": "high",
			},
			"annotations": {
				"genaiops.io/governance-doc": "app_documentation.json",
				"genaiops.io/annex-reference": "Annex III, Nr. 5 lit. a",
				"genaiops.io/oversight-model": "human-in-the-loop",
				"genaiops.io/fria-completed": "true",
				"genaiops.io/drift-detection-enabled": "true",
				"genaiops.io/service-monitor-configured": "true",
				"genaiops.io/evidence-store-connected": "true",
				"genaiops.io/hash-chain-enabled": "true",
				"genaiops.io/evidence-store-type": "postgresql",
				"genaiops.io/eval-passed": "true",
				"genaiops.io/eval-run-id": "eval-20260325-001",
				"genaiops.io/incident-response-configured": "true",
				"genaiops.io/incident-contact": "ai-governance-team@hospital.example.com",
				"genaiops.io/rollback-mechanism": "true",
			},
		},
		"spec": {
			"replicas": 1,
			"selector": {
				"matchLabels": {
					"app.kubernetes.io/name": "ambient-ai-scribe",
				},
			},
			"template": {
				"metadata": {
					"labels": {
						"app.kubernetes.io/name": "ambient-ai-scribe",
						"risk_class": "high",
					},
					"annotations": {
						"genaiops.io/governance-doc": "app_documentation.json",
						"genaiops.io/annex-reference": "Annex III, Nr. 5 lit. a",
						"genaiops.io/oversight-model": "human-in-the-loop",
						"genaiops.io/fria-completed": "true",
						"genaiops.io/drift-detection-enabled": "true",
						"genaiops.io/service-monitor-configured": "true",
						"genaiops.io/evidence-store-connected": "true",
						"genaiops.io/hash-chain-enabled": "true",
						"genaiops.io/eval-passed": "true",
						"genaiops.io/eval-run-id": "eval-20260325-001",
						"genaiops.io/incident-response-configured": "true",
						"genaiops.io/incident-contact": "ai-governance-team@hospital.example.com",
						"genaiops.io/rollback-mechanism": "true",
						"prometheus.io/scrape": "true",
						"prometheus.io/port": "8080",
						"prometheus.io/path": "/metrics",
					},
				},
				"spec": {
					"securityContext": {
						"runAsNonRoot": true,
						"fsGroup": 1000,
					},
					"containers": [
						{
							"name": "scribe",
							"image": "ambient-ai-scribe:1.0.0",
							"ports": [
								{
									"containerPort": 8080,
								},
							],
							"securityContext": {
								"runAsNonRoot": true,
								"runAsUser": 1000,
								"runAsGroup": 1000,
								"allowPrivilegeEscalation": false,
								"readOnlyRootFilesystem": true,
								"capabilities": {
									"drop": [
										"ALL",
									],
								},
							},
							"resources": {
								"requests": {
									"cpu": "100m",
									"memory": "128Mi",
								},
								"limits": {
									"cpu": "500m",
									"memory": "256Mi",
								},
							},
							"volumeMounts": [
								{
									"name": "tmp",
									"mountPath": "/tmp",
								},
							],
						},
					],
					"volumes": [
						{
							"name": "tmp",
							"emptyDir": {},
						},
					],
				},
			},
		},
	}

# --- deployment_incident_fail.json ---
deployment_incident_fail := {
		"_fixture_meta": {
			"description": "FAIL scenario for G-OPS-02 Incident Process Exists (R009)",
			"policy": "policies/operations/policy_incident_process_exists.rego",
			"expected_result": "FAIL — incident-contact missing, rollback-mechanism missing",
			"scenario": "Healthcare Ambient AI Scribe — Gatekeeper rejects deployment without incident config",
			"enforcement": "gatekeeper",
		},
		"review": {
			"object": {
				"apiVersion": "apps/v1",
				"kind": "Deployment",
				"metadata": {
					"name": "ambient-ai-scribe",
					"namespace": "genaiops-healthcare",
				},
				"spec": {
					"template": {
						"metadata": {
							"annotations": {
								"genaiops.io/incident-response-configured": "true",
							},
						},
					},
				},
			},
		},
	}

# --- deployment_incident_pass.json ---
deployment_incident_pass := {
		"_fixture_meta": {
			"description": "PASS scenario for G-OPS-02 Incident Process Exists (R009)",
			"policy": "policies/operations/policy_incident_process_exists.rego",
			"expected_result": "PASS — all incident-response annotations present",
			"scenario": "Healthcare Ambient AI Scribe — Gatekeeper admission with incident config",
			"enforcement": "gatekeeper",
		},
		"review": {
			"object": {
				"apiVersion": "apps/v1",
				"kind": "Deployment",
				"metadata": {
					"name": "ambient-ai-scribe",
					"namespace": "genaiops-healthcare",
				},
				"spec": {
					"template": {
						"metadata": {
							"annotations": {
								"genaiops.io/incident-response-configured": "true",
								"genaiops.io/incident-contact": "ai-governance-team@hospital.example.com",
								"genaiops.io/rollback-mechanism": "true",
							},
						},
					},
				},
			},
		},
	}

# --- deployment_noncompliant.yaml ---
deployment_noncompliant := {
		"apiVersion": "apps/v1",
		"kind": "Deployment",
		"metadata": {
			"name": "ambient-ai-scribe-bad",
			"namespace": "genaiops",
			"labels": {
				"app.kubernetes.io/name": "ambient-ai-scribe",
			},
		},
		"spec": {
			"replicas": 1,
			"selector": {
				"matchLabels": {
					"app.kubernetes.io/name": "ambient-ai-scribe",
				},
			},
			"template": {
				"metadata": {
					"labels": {
						"app.kubernetes.io/name": "ambient-ai-scribe",
					},
					"annotations": {
						"prometheus.io/scrape": "true",
					},
				},
				"spec": {
					"containers": [
						{
							"name": "scribe",
							"image": "ambient-ai-scribe:1.0.0",
							"ports": [
								{
									"containerPort": 8080,
								},
							],
							"env": [
								{
									"name": "DB_PASSWORD",
									"value": "super-secret-password-123",
								},
								{
									"name": "API_KEY",
									"value": "sk-1234567890abcdef",
								},
							],
							"securityContext": {
								"runAsNonRoot": false,
								"runAsUser": 0,
								"allowPrivilegeEscalation": true,
								"readOnlyRootFilesystem": false,
							},
						},
					],
				},
			},
		},
	}

# --- eval_results.json ---
eval_results := {
		"evaluation": {
			"model_name": "gpt-4o-mini",
			"model_version": "mock-v1.0.0",
			"pipeline_id": "ci-main-42",
			"run_id": "eval-20260325-001",
			"evaluated_at": "2026-03-25T10:00:00Z",
		},
		"quality_metrics": {
			"accuracy": 0.91,
			"faithfulness_score": 0.94,
			"relevance_score": 0.89,
			"coherence_score": 0.92,
		},
		"performance_metrics": {
			"latency_p50_ms": 320,
			"latency_p95_ms": 890,
			"latency_p99_ms": 1450,
			"throughput_rps": 12.5,
		},
		"safety_metrics": {
			"safety_score": 0.96,
			"toxicity_score": 0.01,
			"hallucination_rate": 0.04,
			"prompt_injection_resistance": 0.98,
		},
		"subgroup_analysis": {
			"performed": true,
			"subgroups": [
				"age_group",
				"gender",
				"language",
				"medical_specialty",
			],
			"worst_group_accuracy": 0.87,
			"worst_group_name": "language:non_native",
			"bias_detected": false,
		},
		"adversarial_tests": {
			"performed": true,
			"prompt_injection_pass_rate": 0.95,
			"jailbreak_resistance": 0.98,
			"data_extraction_resistance": 0.99,
			"test_suite_version": "adversarial-v1.0",
		},
		"gate_thresholds": {
			"accuracy_min": 0.85,
			"latency_p95_max_ms": 2000,
			"safety_score_min": 0.9,
		},
		"gate_result": {
			"all_passed": true,
			"details": [
				{
					"metric": "accuracy",
					"value": 0.91,
					"threshold": 0.85,
					"result": "PASS",
				},
				{
					"metric": "latency_p95",
					"value": 890,
					"threshold": 2000,
					"result": "PASS",
				},
				{
					"metric": "safety_score",
					"value": 0.96,
					"threshold": 0.9,
					"result": "PASS",
				},
			],
		},
	}

# --- eval_results_fail.json ---
eval_results_fail := {
		"evaluation": {
			"model_name": "gpt-4o-mini",
			"model_version": "mock-v1.0.0",
			"pipeline_id": "ci-main-43",
			"run_id": "eval-20260325-002",
			"evaluated_at": "2026-03-25T14:00:00Z",
		},
		"quality_metrics": {
			"accuracy": 0.72,
			"faithfulness_score": 0.68,
			"relevance_score": 0.75,
			"coherence_score": 0.8,
		},
		"performance_metrics": {
			"latency_p50_ms": 1200,
			"latency_p95_ms": 2800,
			"latency_p99_ms": 4500,
			"throughput_rps": 3.1,
		},
		"safety_metrics": {
			"safety_score": 0.78,
			"toxicity_score": 0.08,
			"hallucination_rate": 0.15,
			"prompt_injection_resistance": 0.82,
		},
		"subgroup_analysis": {
			"performed": false,
			"subgroups": [],
			"worst_group_accuracy": null,
			"worst_group_name": "",
			"bias_detected": false,
		},
		"adversarial_tests": {
			"performed": false,
			"prompt_injection_pass_rate": null,
			"jailbreak_resistance": null,
			"data_extraction_resistance": null,
			"test_suite_version": "",
		},
		"gate_thresholds": {
			"accuracy_min": 0.85,
			"latency_p95_max_ms": 2000,
			"safety_score_min": 0.9,
		},
		"gate_result": {
			"all_passed": false,
			"details": [
				{
					"metric": "accuracy",
					"value": 0.72,
					"threshold": 0.85,
					"result": "FAIL",
				},
				{
					"metric": "latency_p95",
					"value": 2800,
					"threshold": 2000,
					"result": "FAIL",
				},
				{
					"metric": "safety_score",
					"value": 0.78,
					"threshold": 0.9,
					"result": "FAIL",
				},
			],
		},
	}

# --- model_documentation_bias_fail.json ---
model_documentation_bias_fail := {
		"_fixture_meta": {
			"description": "FAIL scenario for G-DEP-05 Bias Assessment Complete (R013)",
			"policy": "policies/pre-deployment/policy_bias_assessment_complete.rego",
			"expected_result": "FAIL — bias detected but mitigation_measures missing",
			"scenario": "Healthcare Ambient AI Scribe — bias detected in age_group, no mitigation documented",
		},
		"bias_detection": {
			"methods": [
				"counterfactual_fairness_test",
			],
			"protected_attributes": [
				"gender",
				"age_group",
			],
			"fairness_results": {
				"bias_detected": true,
				"metrics": [
					{
						"name": "demographic_parity_difference",
						"value": 0.18,
						"threshold": 0.1,
						"passed": false,
					},
				],
				"evaluation_date": "2026-03-15",
			},
		},
	}

# --- model_documentation_bias_pass.json ---
model_documentation_bias_pass := {
		"_fixture_meta": {
			"description": "PASS scenario for G-DEP-05 Bias Assessment Complete (R013)",
			"policy": "policies/pre-deployment/policy_bias_assessment_complete.rego",
			"expected_result": "PASS — all bias documentation requirements met",
			"scenario": "Healthcare Ambient AI Scribe — bias assessment performed with no critical bias detected",
		},
		"bias_detection": {
			"methods": [
				"counterfactual_fairness_test",
				"disparate_impact_analysis",
			],
			"protected_attributes": [
				"gender",
				"age_group",
				"primary_language",
			],
			"fairness_results": {
				"bias_detected": false,
				"metrics": [
					{
						"name": "demographic_parity_difference",
						"value": 0.03,
						"threshold": 0.1,
						"passed": true,
					},
					{
						"name": "equalized_odds_difference",
						"value": 0.02,
						"threshold": 0.1,
						"passed": true,
					},
				],
				"evaluation_date": "2026-03-15",
				"evaluated_by": "ML Engineer — Fairness Pipeline v1.0",
			},
			"mitigation_measures": [],
		},
	}
